### PR TITLE
Add translation to plugin name

### LINKED ISSUE #38: Default sort order is different from WP's plugin page
https://wordpress.org/support/topic/order-of-the-plugins-is-different-compared-to-the-plugin-list/

This probably has to do with WP sorting by slug (which would add "-" for spaces), whereas PR sorts strictly by the content of the table cells in the column.

@Zodiac1978 Since you implemented table sorting, perhaps you'd like to see whether this low hanging fruit?

### PR DESCRIPTION
**Pull request by Zodiac1978**
First attempt on using translated plugin data if available.

Fixes #38

### CODE REVIEW

**Comment by Zodiac1978** [comment]
Now I see the exact same result for the plugin table as in Plugin Report. Plugin Name is translated and whitespace are fixed.

I don't find any more edge cases. Ready for review!

**Comment by roytanck** [comment]
@Zodiac1978 I'm sorry for not looking at this sooner. It's been a crazy couple of weeks. This looks ready to merge, so I'll try to do a new release as soon as I find the time.

Thank you once again for figuring this all out and preparing the PR!

**Comment by Zodiac1978** [comment]
No problem @roytanck - this is not a critical bug, just more consistent behavior. No need to hurry ...

It was fun to debug this issue. :)

**Comment by roytanck** [comment]
@Zodiac1978 I'm wondering why you're using `translate()` directly, instead of '__()`. The developer docs for translate() clearly state "Don’t use translate() directly, use __() or related functions.".

**Comment by Zodiac1978** [comment]
> I'm wondering why you're using translate() directly, instead of '__()`.

I think this is an edge case. Using `__()` is recommended because the WP.org parser and tools like PoEdit are looking for these functions, but as we don't want to add those strings to the translation file of "Plugin Report" I think this is the correct to solve this. We are mimicking core behavior and are using core code to translate the plugin info and do not want to add these strings to the library of **our** plugin.

Looking from the feature set there is nothing lost here. `__()` is just a wrapper:
```
function __( $text, $domain = 'default' ) {
    return translate( $text, $domain );
}
```

I do not think this is a high risk, but maybe we could use `esc_html()` on this string. Wondering if this happens in the WP core code higher or lower in the chain.

**Comment by roytanck** [comment]
Oops, I changed it to __() before releasing 1.9. Wordpress org does not appear to show any new string though. If this turns out to cause issues, I'll have to do a quick 1.9.1.

**Comment by Zodiac1978** [comment]
> Wordpress org does not appear to show any new string though.

We should check tools like "Loco Translate" too. Using more than one text domain is not recommended. Maybe this warning could appear now. But nothing critical. As this is using a variable for the text domain the parser should fail for these strings already. 

This is the reason why there is a `phpcs:ignore` in the line before by the way ...

**Comment by roytanck** [comment]
I'll reverse the change later today and do a quick release.

**Pull request merged**
